### ISSUE TITLE
Missing resource in your project

### ISSUE THREAD

**Issue by ilentt** [frenmanoj/bookstore#1]
I have try implement  your project following your tutorial but I did not find any resource in your project  including these file listed below:

```
<link rel="stylesheet"
    href='<c:url value="/web-resources/css/pure-0.4.2.css"/>'>

<link rel="stylesheet"
    href='<c:url value="/web-resources/css/font-awesome-4.0.3/css/font-awesome.css"/>'>
<link rel="stylesheet"
    href='<c:url value="/web-resources/css/jquery-ui-1.10.4.custom.css"/>'>
```

would you please update again?

**Comment by frenmanoj** [comment]
I've double checked, it's working perfectly fine. Please make sure you have the following mapping in your [`servlet-context.xml`](https://github.com/frenmanoj/bookstore/blob/master/src/main/webapp/WEB-INF/spring/dispatcherServlet/servlet-context.xml).

`<resources mapping="/web-resources/**" location="/resources/" />`
